"""refactor_question_model

Revision ID: 6cf88477d4ff
Revises: e71fdb72d468
Create Date: 2026-08-14 02:28:52.269847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cf88477d4ff'
down_revision: Union[str, Sequence[str], None] = 'e71fdb72d468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('chapter', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('media', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.create_index(op.f('ix_questions_code'), ['code'], unique=True)
        batch_op.drop_column('image_url')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('correct_option')
        batch_op.drop_column('latex_code')
        batch_op.drop_column('sample_solution')
        batch_op.drop_column('blanks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('blanks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('sample_solution', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('latex_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('correct_option', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_questions_code'), table_name='questions')
    op.drop_column('questions', 'tags')
    op.drop_column('questions', 'correct_answers')
    op.drop_column('questions', 'media')
    op.drop_column('questions', 'topic')
    op.drop_column('questions', 'chapter')
    op.drop_column('questions', 'code')
    # ### end Alembic commands ###
