"""add_classroom_code_and_advanced_features

Revision ID: afead183569f
Revises: 6cf88477d4ff
Create Date: 2026-08-15 22:21:17.684823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afead183569f'
down_revision: Union[str, Sequence[str], None] = '6cf88477d4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use batch mode for SQLite support
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True))
        batch_op.create_index(op.f('ix_classrooms_code'), ['code'], unique=True)
        # Drop and recreate FK
        batch_op.create_foreign_key('fk_classrooms_instructor_id_users', 'users', ['instructor_id'], ['id'], ondelete='CASCADE')

    op.create_table('classroom_exams',
        sa.Column('classroom_id', sa.Integer(), nullable=False),
        sa.Column('exam_id', sa.Integer(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
        sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('classroom_id', 'exam_id')
    )
    op.create_table('classroom_students',
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('classroom_id', sa.Integer(), nullable=False),
        sa.Column('joined_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
        sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('student_id', 'classroom_id')
    )
    op.drop_table('student_classrooms')
    op.add_column('assignments', sa.Column('assigned_at', sa.DateTime(timezone=True), server_default='now()', nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classrooms', type_='foreignkey')
    op.create_foreign_key(None, 'classrooms', 'users', ['instructor_id'], ['id'])
    op.drop_index(op.f('ix_classrooms_code'), table_name='classrooms')
    op.drop_column('classrooms', 'created_at')
    op.drop_column('classrooms', 'code')
    op.drop_column('classrooms', 'description')
    op.drop_column('assignments', 'assigned_at')
    op.create_table('student_classrooms',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('classroom_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'classroom_id')
    )
    op.drop_table('classroom_students')
    op.drop_table('classroom_exams')
    # ### end Alembic commands ###
