"""Add soft delete to User, Exam, Classroom

Revision ID: eec75b033abc
Revises: ba4176d5ac3c
Create Date: 2026-08-17 03:53:58.660666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec75b033abc'
down_revision: Union[str, Sequence[str], None] = 'ba4176d5ac3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classrooms', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('exams', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('exams', 'is_deleted')
    op.drop_column('classrooms', 'is_deleted')
    # ### end Alembic commands ###
