"""add_indexes_to_models

Revision ID: ef52ffee864a
Revises: eec75b033abc
Create Date: 2026-08-17 04:26:10.917554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef52ffee864a'
down_revision: Union[str, Sequence[str], None] = 'eec75b033abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('open_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_assignments_classroom_id'), 'assignments', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_assignments_due_date'), 'assignments', ['due_date'], unique=False)
    op.create_index(op.f('ix_assignments_exam_id'), 'assignments', ['exam_id'], unique=False)
    op.create_index(op.f('ix_assignments_is_active'), 'assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_assignments_open_date'), 'assignments', ['open_date'], unique=False)
    op.create_index(op.f('ix_classroom_students_classroom_id'), 'classroom_students', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_classroom_students_is_active'), 'classroom_students', ['is_active'], unique=False)
    op.create_index(op.f('ix_classroom_students_student_id'), 'classroom_students', ['student_id'], unique=False)
    op.create_index(op.f('ix_classrooms_instructor_id'), 'classrooms', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_classrooms_is_deleted'), 'classrooms', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_exam_submissions_exam_id'), 'exam_submissions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_submissions_grading_status'), 'exam_submissions', ['grading_status'], unique=False)
    op.create_index(op.f('ix_exam_submissions_submitted_at'), 'exam_submissions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_exam_submissions_user_id'), 'exam_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_exams_created_by_id'), 'exams', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_exams_is_deleted'), 'exams', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_exams_is_published'), 'exams', ['is_published'], unique=False)
    op.create_index(op.f('ix_questions_created_by_id'), 'questions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_grade_level'), 'questions', ['grade_level'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_index(op.f('ix_users_grade_level'), 'users', ['grade_level'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_grade_level'), table_name='users')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_grade_level'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_by_id'), table_name='questions')
    op.drop_index(op.f('ix_exams_is_published'), table_name='exams')
    op.drop_index(op.f('ix_exams_is_deleted'), table_name='exams')
    op.drop_index(op.f('ix_exams_created_by_id'), table_name='exams')
    op.drop_index(op.f('ix_exam_submissions_user_id'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_submitted_at'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_grading_status'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_exam_id'), table_name='exam_submissions')
    op.drop_index(op.f('ix_classrooms_is_deleted'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_instructor_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classroom_students_student_id'), table_name='classroom_students')
    op.drop_index(op.f('ix_classroom_students_is_active'), table_name='classroom_students')
    op.drop_index(op.f('ix_classroom_students_classroom_id'), table_name='classroom_students')
    op.drop_index(op.f('ix_assignments_open_date'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_is_active'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_exam_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_due_date'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_classroom_id'), table_name='assignments')
    op.drop_column('assignments', 'open_date')
    # ### end Alembic commands ###
